import { config } from 'dotenv';
import { APIS } from './api-config';

export { APIS };

config({ path: `.env.${process.env.NODE_ENV || 'development'}.local` });

export const CREDENTIALS = process.env.CREDENTIALS === 'true';
export const SWAGGER_ENABLED = process.env.SWAGGER_ENABLED === 'true';
export const SESSION_MEMORY = process.env.SESSION_MEMORY === 'true';

export const {
  NODE_ENV,
  PORT,
  API_BASE_URL,
  AZURE_REGION,
  AZURE_SUBSCRIPTION_KEY,
  AZURE_TRANSLATOR_KEY,
  INTRIC_API_BASE_URL,
  INTRIC_API_BASE_PATH,
  INTRIC_SALT,
  INTRIC_APIKEY_VUX,
  INTRIC_APIKEY_SERVANET,
  INTRIC_APIKEY_PRATOMAT1,
  INTRIC_APIKEY_PRATOMAT2,
  INTRIC_APIKEY_PRATOMAT3,
  INTRIC_APIKEY_PRATOMAT4,
  INTRIC_APIKEY_PRATOMAT5,
  INTRIC_APIKEY_PRATOMAT6,
  INTRIC_APIKEY_PRATOMAT7,
  INTRIC_APIKEY_PRATOMAT8,
  INTRIC_APIKEY_PRATOMAT9,
  INTRIC_APIKEY_QWERTY,
  INTRIC_APIKEY_WISSER,
  APPLICATION_MODE,
  RATE_LIMIT_WINDOW,
  RATE_LIMIT_MAX,
  SPIKE_LIMIT_WINDOW,
  SPIKE_LIMIT_MAX,
  LOG_FORMAT,
  LOG_DIR,
  ORIGIN,
  SECRET_KEY,
  CLIENT_KEY,
  CLIENT_SECRET,
  BASE_URL_PREFIX,
  SAML_CALLBACK_URL,
  SAML_LOGOUT_CALLBACK_URL,
  SAML_FAILURE_REDIRECT,
  SAML_ENTRY_SSO,
  SAML_ISSUER,
  SAML_IDP_PUBLIC_CERT,
  SAML_PRIVATE_KEY,
  SAML_PUBLIC_KEY,
} = process.env;
